# Site settings
title: "APR Project"
url: "https://lec4.github.io/apr_project/"  # Replace with your GitHub Pages URL
author: Lily Codd # Your name

# Theme settings
theme: jekyll-theme-cayman # You can replace this with other supported GitHub Pages themes like jekyll-theme-cayman, slate, etc.

header_pages:
  - data.md
  - methodology.md
  - results.md
  - conclusions.md
  
# Optional plugins
plugins:
  - jekyll-feed  # This plugin adds an RSS feed to your site
  - jekyll-seo-tag  # Adds SEO optimization tags to your site
  - jekyll-sitemap  # Automatically generates a sitemap



# Markdown settings
markdown: kramdown  # Default for GitHub Pages
highlighter: rouge  # Syntax highlighting for code blocks

# Build settings (optional)
future: true  # Show future-dated posts
